{% set name = "gita" %}
{% set version = "0.16.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gita-{{ version }}.tar.gz
  sha256: 99b60b7d732cb857f2f168b7f60c6bed04aaf67f5811dea2135d23174149b7a5

build:
  entry_points:
    - gita = gita.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - packaging
    - python >={{ python_min }}
    - argcomplete

test:
  imports:
    - gita
  commands:
    - pip check
    - gita --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nosarthur/gita
  summary: Manage multiple git repos with sanity
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
