{% set name = "gita" %}
{% set version = "0.16.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gita-{{ version }}.tar.gz
  sha256: ad0c0f4c7d7f59c477dd8c1115b081b0b45ab7d4ef2e0d599403a07e87d19016

build:
  entry_points:
    - gita = gita.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - argcomplete

test:
  imports:
    - gita
  commands:
    - pip check
    - gita --help
  requires:
    - pip

about:
  home: https://github.com/nosarthur/gita
  summary: Manage multiple git repos with sanity
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
